# name: Calculate code coverage

# on:   
#   push:
#     branches:
#       - master

# jobs:
#   pytest_coverage:
#     runs-on: ubuntu-20.04
#     steps:
#       - uses: actions/checkout@v3
#       - name: Set up Python 3.10
#         uses: actions/setup-python@v3
#         with:
#           python-version: 3.10.6
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#           pip install pytest
#           pip install pytest-cov
#           pip install gcovr
#           pip install wheel
#       - name: Install the package your are testing.
#         run: |
#           export COVERAGE=1
#           pip install --no-build-isolation .
#       - name: Get coverage
#         run: |
#           pytest --cov-config=.coveragec --cov=mlxp --cov-report xml:coverage.xml
#           PYTHON_COVERAGE=$( xmllint --xpath 'string(/coverage/@line-rate)' coverage.xml)
#           echo $PYTHON_COVERAGE
#           test=$(echo "$PYTHON_COVERAGE < 0.8" | bc)
#           if ((test)); then echo "Failed because of python coverage";exit 1; fi