name: Sphinx build

on: 
  push: 
    branches: 
      - master
      - develop

jobs:
  build:
    #runs-on: ubuntu-22.04
    runs-on: self-hosted
    env:
        AGENT_TOOLSDIRECTORY: /usr/local/bin/
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python environment
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Update pip
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install the package your documenting together with its dependencies.
      run: |
        pip install .
    - name: Install the building dependencies.
    # With higher version of docutils bullet lists does not work
      run: |
        pip install sphinx furo autodocsumm
    - name: Build the sphinx documentation and posts warnings as github comments.
      run: cd docs && sphinx-build -b html . _build/html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/sphinx/source/_build/html